context:
  version: "0.87.1"

package:
  name: baml-py
  version: ${{ version }}

source:
  - url: https://github.com/BoundaryML/baml/archive/refs/tags/${{ version }}.tar.gz
    sha256: 918047c28436dd64061ea5be8638d2d39f164ef3d4cc0cede019b9410d3adb14

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - perl
    - make
  host:
    - python
    - pip
    - maturin
  run:
    - python

tests:
  - python:
      imports:
        - baml_py
      pip_check: true

about:
  homepage: https://github.com/BoundaryML/baml
  summary: BAML is a language that helps you get structured data from LLMs, with the best DX possible.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
