context:
  version: "0.207.1"

package:
  name: baml-py
  version: ${{ version }}

source:
  - url: https://github.com/BoundaryML/baml/archive/refs/tags/${{ version }}.tar.gz
    sha256: 82d2b962f720514ae8c2259175e4a7ae855b3e04c1e329c81da49ef2bb33f21c

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - perl
    - make
  host:
    - python
    - pip
    - maturin
  run:
    - python

tests:
  - python:
      imports:
        - baml_py
      pip_check: true

about:
  homepage: https://github.com/BoundaryML/baml
  summary: BAML is a language that helps you get structured data from LLMs, with the best DX possible.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
